# Generated by Django 5.0.6 on 2024-05-31 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='flight_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
    ]
